<?php

namespace GestionCarteBundle\Repository;

/**
 * CarteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByPorteur($num)
    {
        return $this->createQueryBuilder('cr')
            ->where('(cr.num_carte=:carte) OR (cr.num_supcarte=:carte)')
            ->setParameter('carte',$num)
            ->orderBy('cr.nom_porteur')
            ->getQuery()
            ->getResult();
    }
}
