<?php

namespace GestionTransactionBundle\Repository;

/**
 * TPERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TPERepository extends \Doctrine\ORM\EntityRepository
{
}
