<?php

namespace GestionTransactionBundle\Repository;

/**
 * Type_TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_TransactionRepository extends \Doctrine\ORM\EntityRepository
{
}
