imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@GestionAccesBundle/Resources/config/services.xml" }
    - { resource: "@GestionCarteBundle/Resources/config/services.xml" }
    - { resource: "@GestionTransactionBundle/Resources/config/services.xml" }
    - { resource: "@ReportingBundle/Resources/config/services.xml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            #Mysql
            default:
               driver:   "%pgsql_database_driver%"
               host:     "%pgsql_database_host%"
               port:     "%pgsql_database_port%"
               dbname:   "%pgsql_database_name%"
               user:     "%pgsql_database_user%"
               password: "%pgsql_database_password%"
               charset:  UTF8

            #Postgresql
            pgsql:
                driver:   "%pgsql_database_driver%"
                host:     "%pgsql_database_host%"
                port:     "%pgsql_database_port%"
                dbname:   "%pgsql_database_name%"
                user:     "%pgsql_database_user%"
                password: "%pgsql_database_password%"
                charset:  UTF8

    orm:
        default_entity_manager: pgsql
        auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true

        entity_managers:
            default:
                connection: default

                # lister les Bundles utilisant la connexion par defaut

                #mappings:
                    #monprojetmysqlBundle:  ~
                    #tutoUserBundle:  ~


            pgsql:
                connection: pgsql    # connection name for your additional DB

                # bundles utilisant la connexion Postgresql
                mappings:
                    GestionAccesBundle: ~
                    GestionCarteBundle: ~
                    GestionTransactionBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: 25
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: {type: memory}

