<?php

namespace GestionAccesBundle\Repository;

/**
 * FonctionaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FonctionaliteRepository extends \Doctrine\ORM\EntityRepository
{
}
