<?php

namespace GestionAccesBundle\Repository;

/**
 * Profil_FNRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Profil_FNRepository extends \Doctrine\ORM\EntityRepository
{
}
